const PageRoutes = {
  home: "/",
  allMembers: "/members",
  memberProfile: (id: number) => "/members/" + id,
  publicPartnerProfile: (id: number) => "/partners/" + id + "/public",
  organizationProfile: (id: number) => "/partners/" + id + "/public",
  publicMemberProfile: (id: number) => "/members/" + id + "/public",
  publicProductProfile: (id: number) => "/products/" + id + "/public",
  privateMemberProfile: (id: number) => "/members/" + id + "/private",
  privateProductProfile: (id: number) => "/products/" + id + "/private",
  productProfile: (id: number) => "/products/" + id + "/public",
  grantProfile: (id: number) => "/grants/" + id + "/public",
  eventProfile: (id: number) => "/events/" + id + "/public",
  myProfile: "/my-profile",
  allAccounts: "/accounts",
  allPartners: "/partners",
  allProducts: "/products",
  allEvents: "/events",
  products: "/products",
  allGrants: "/grants",
  allSupervisions: "/supervisions",
  accountProfile: (id: number) => "/accounts/" + id,
  register: "/register",
  _404: "/404",
} as const;

export default PageRoutes;
